name: stickynotes
title: Sticky Notes
base: core24
version: '1.0.0'
summary: A simple and elegant sticky notes app for your desktop.
description: |
  Sticky Notes is a lightweight note-taking application
  for your Linux desktop. Run it from the system tray,
  create multiple notes, and enjoy automatic saving between sessions.
  Built with Python and PyQt6.

grade: stable
confinement: strict

license: MIT
contact: https://github.com/dstushar7
website: https://github.com/dstushar7
source-code: https://github.com/dstushar7/sticky-notes-qt6
issues: https://github.com/dstushar7/sticky-notes-qt6/issues
donation: https://www.buymeacoffee.com/dstushar7

apps:
  stickynotes:
    command: qt6-launch $SNAP/bin/python3 $SNAP/run_stickynotes.py
    desktop: gui/stickynotes.desktop
    plugs: [desktop, desktop-legacy, x11, wayland, unity7, home]

parts:
  stickynotes:
    plugin: python
    source: .
    python-packages:
      - PyQt6
      - PyQt6-Qt6
      - PyQt6_sip
    stage-packages:
      - qt6-qpa-plugins
      - python3-pyqt6
      - libqt6core6
      - libqt6gui6
      - libqt6network6
      - libqt6widgets6
      - libgl1
      - libxcb1
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb1-dev
      - libxcb-cursor0
    build-packages:
      - python3-dev
    override-build: |
      craftctl default
      cp -r $CRAFT_PROJECT_DIR/stickynotes $CRAFT_PART_INSTALL/
      cp $CRAFT_PROJECT_DIR/run_stickynotes.py $CRAFT_PART_INSTALL/
      cp $CRAFT_PROJECT_DIR/snap/qt6-launch $CRAFT_PART_INSTALL/
    override-prime: |
      craftctl default
      cp -r $CRAFT_PROJECT_DIR/snap/gui $CRAFT_PRIME/