name: sticky-notes-qt6
base: core24
version: '1.0'
summary: A modern Qt6 sticky notes app with autosave and tray icon
description: |
  A feature-rich sticky notes application built with PyQt6 that helps you organize your workspace and notes easily.

grade: stable
confinement: strict

license: MIT
contact: https://github.com/dstushar7
website: https://github.com/dstushar7
source-code: https://github.com/dstushar7/sticky-notes-qt6
issues: https://github.com/dstushar7/sticky-notes-qt6/issues
donation: https://www.buymeacoffee.com/dstushar7

apps:
  sticky-notes-qt6:
    command: qt6-launch $SNAP/bin/python3 $SNAP/run_stickynotes.py
    desktop: $SNAP/snap/gui/sticky-notes.desktop
    plugs: [desktop, desktop-legacy, x11, wayland, unity7, home]

parts:
  sticky-notes-qt6:
    plugin: python
    source: .
    python-packages:
      - PyQt6
      - PyQt6-Qt6
      - PyQt6_sip
    stage-packages:
      - python3-pyqt6
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - qt6-gtk-platformtheme
      - libgl1
      - libxcb1
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb1-dev
    build-packages:
      - python3-dev
    override-build: |
      craftctl default
      cp $CRAFT_PROJECT_DIR/run_stickynotes.py $CRAFT_PART_INSTALL/
      cp $CRAFT_PROJECT_DIR/snap/qt6-launch $CRAFT_PART_INSTALL/