# # A unique, lowercase name for your app on the Snap Store.
# name: yourname-stickynotes # <-- IMPORTANT: Change this to your registered name.
# base: core22
# version: '1.0'
# summary: A simple and elegant sticky notes app for your desktop.
# description: |
#   A lightweight sticky notes app that runs in the system tray. Notes are
#   automatically saved and restored across sessions.

# grade: stable
# confinement: strict

# apps:
#   yourname-stickynotes: # <-- IMPORTANT: Change this to match the 'name' above.
#     # The command now directly calls the Python entry point.
#     command: venv/bin/python3 run_stickynotes.py
    
#     # Essential permissions for a desktop GUI application.
#     plugs:
#       - desktop
#       - desktop-legacy
#       - wayland
#       - x11

# parts:
#   stickynotes-app:
#     plugin: python
#     source: . # Use the code from the current project directory.
    
#     # Python dependencies for your application.
#     python-packages:
#       - PyQt6
      
#     # Essential system libraries required for PyQt6 to run correctly.
#     # Without these, you will get the 'xcb platform plugin' error.
#     stage-packages:
#       - libxcb-cursor0
#       - libxkbcommon-x11-0
#       - libgl1-mesa-glx